### ISSUE TITLE
思政网code review

### ISSUE THREAD

**Issue by zxc0328** [shengxihu/sizheng#1]
1.比上次好一些，但是css还是有4级甚至5级的状况，这个是完全可以避免的。

2.我最后要你改的那个圆角的标题，这个东西的样式基本是一样的啊，css里你就写一个class就行了，不用重复使用。然后你把`display`设成`inline-block`的话，只要设置两边的边距就可以让这个宽度自适应了。宽度就是里面文字+边距，完全不用自己显式声明，这个只用写一遍样式，然后写起来也简单。
这个是编程里一个很重要的点：Don't repeat yourself，不用重复。能整合的就整合。写代码是资源敏感的，就是存储空间，计算资源这些。所以你要培养一下你的习惯。

3.banner里面的图片，在现实中图片的大小是五花八门的，你如果不加以限制，那肯定就会溢出边框了。所以你要给图片设置`width:100%; min-height:100%;`然后在父元素上`overflow:hidden;`

4.有些地方的`display`属性还是用的不对。有些box就是一个正常文档流的顺序，你给一个`inline-block`压根没什么用。

**Comment by Glowin** [comment]
:+1: 分析的很中肯

**Comment by shengxihu** [comment]
>学习中，谢谢。
